"""Sentinel read-only evidence surface."""

from .attention import build_attention_snapshot, build_attention_snapshot_from_case
from .attention_config import DEFAULT_ATTENTION_CONFIG, resolve_attention_config
from .chain import SENTINEL_CHAIN_DRY_RUN_SCHEMA_VERSION, run_sentinel_chain_dry_run
from .evidence import SentinelEvidenceService, SentinelEvidenceView, sentinel_evidence_service
from .eval import (
    ATTENTION_SNAPSHOT_SCHEMA_VERSION,
    DEFAULT_SENTINEL_REPLAY_TRACE_DIR,
    SENTINEL_REPLAY_EVAL_SCHEMA_VERSION,
    attention_snapshot_builder,
    evaluate_case,
    evaluate_cases,
)
from .handoff import (
    LAYER2_HANDOFF_ALLOWED_FIELDS,
    LAYER2_HANDOFF_SCHEMA_VERSION,
    LAYER2_HANDOFF_SOURCE_FIELDS,
    build_layer2_handoff,
)
from .gate import (
    GATE_ACTION_ALLOW_CORE_WAKE,
    GATE_ACTION_BLOCK_CORE_WAKE,
    GATE_ACTION_OBSERVE,
    GATE_REASON_CHAT_COOLDOWN,
    GATE_REASON_CLEAR_SLEEP,
    GATE_REASON_DEVICE_GATE,
    GATE_REASON_LOW_CONFIDENCE,
    GATE_REASON_QUIET_HOURS,
    GATE_REASON_WAKE_COOLDOWN,
    GATE_STATUS_BLOCKED,
    GATE_STATUS_NOT_REQUESTED,
    GATE_STATUS_PASSED,
    SENTINEL_GATE_RESULT_SCHEMA_VERSION,
    WAKE_BOUNDARY_RESULT_SCHEMA_VERSION,
    evaluate_sentinel_gate,
    evaluate_wake_boundaries,
)
from .judgment import (
    REQUIRED_SENTINEL_JUDGMENT_FIELDS,
    SENTINEL_JUDGMENT_PROMPT_VERSION,
    SENTINEL_JUDGMENT_SCHEMA_VERSION,
    build_sentinel_judgment_messages,
    judgment_to_monitor_log_fields,
    normalize_sentinel_judgment,
    parse_sentinel_judgment,
)
from .judgment_eval import (
    DEFAULT_SENTINEL_JUDGMENT_TRACE_DIR,
    SENTINEL_JUDGMENT_EVAL_SCHEMA_VERSION,
    actual_judgment_payload,
    evaluate_judgment_case,
    evaluate_judgment_cases,
    evaluate_judgment_expectations,
)
from .judgment_runner import (
    SENTINEL_JUDGMENT_RUN_SCHEMA_VERSION,
    SentinelJudgmentProvider,
    run_sentinel_judgment_dry_run,
)
from .runtime_context import (
    LEGACY_SENTINEL_RUNTIME_CONTEXT_SCHEMA_VERSION,
    SENTINEL_RUNTIME_CONTEXT_SCHEMA_VERSION,
    SUPPORTED_SENTINEL_RUNTIME_CONTEXT_SCHEMA_VERSIONS,
    build_sentinel_runtime_context,
    validate_sentinel_runtime_context,
)
from .core_wake_orchestrator import (
    CORE_WAKE_EXECUTION_MODE_DISABLED,
    CORE_WAKE_EXECUTION_MODE_DRY_RUN,
    CORE_WAKE_EXECUTION_MODE_FULL,
    CORE_WAKE_EXECUTION_MODE_TEST_EXECUTE,
    CORE_WAKE_EXECUTION_SCHEMA_VERSION,
    CORE_WAKE_EXECUTION_STEP_DEFINITIONS,
    CORE_WAKE_PREFLIGHT_SCHEMA_VERSION,
    DEFAULT_CORE_WAKE_HISTORY_LIMIT,
    DEFAULT_CORE_WAKE_MESSAGE_MAX_CHARS,
    PLANNED_CORE_WAKE_PRODUCTION_EFFECTS,
    build_core_wake_preflight,
    run_core_wake_orchestrator_dry_run,
    run_core_wake_orchestrator_full_execute,
    run_core_wake_orchestrator_test_execute,
)
from .core_wake_ports import (
    CORE_WAKE_PORT_METHODS,
    CoreWakePorts,
    stored_message_to_dict,
    validate_core_wake_ports,
)
from .wake_package import (
    CORE_WAKE_HARD_LIMITS,
    CORE_WAKE_PACKAGE_SCHEMA_VERSION,
    LEGACY_CORE_WAKE_PACKAGE_SCHEMA_VERSION,
    SUPPORTED_CORE_WAKE_PACKAGE_SCHEMA_VERSIONS,
    build_core_wake_package,
)
from .sources import EvidenceRecord, ReplayEvidenceBundle, adapt_replay_input


__all__ = [
    "ATTENTION_SNAPSHOT_SCHEMA_VERSION",
    "CORE_WAKE_EXECUTION_MODE_DISABLED",
    "CORE_WAKE_EXECUTION_MODE_DRY_RUN",
    "CORE_WAKE_EXECUTION_MODE_FULL",
    "CORE_WAKE_EXECUTION_MODE_TEST_EXECUTE",
    "CORE_WAKE_EXECUTION_SCHEMA_VERSION",
    "CORE_WAKE_EXECUTION_STEP_DEFINITIONS",
    "CORE_WAKE_HARD_LIMITS",
    "CORE_WAKE_PACKAGE_SCHEMA_VERSION",
    "CORE_WAKE_PREFLIGHT_SCHEMA_VERSION",
    "CORE_WAKE_PORT_METHODS",
    "DEFAULT_ATTENTION_CONFIG",
    "DEFAULT_CORE_WAKE_HISTORY_LIMIT",
    "DEFAULT_CORE_WAKE_MESSAGE_MAX_CHARS",
    "DEFAULT_SENTINEL_JUDGMENT_TRACE_DIR",
    "DEFAULT_SENTINEL_REPLAY_TRACE_DIR",
    "EvidenceRecord",
    "GATE_ACTION_ALLOW_CORE_WAKE",
    "GATE_ACTION_BLOCK_CORE_WAKE",
    "GATE_ACTION_OBSERVE",
    "GATE_REASON_CHAT_COOLDOWN",
    "GATE_REASON_CLEAR_SLEEP",
    "GATE_REASON_DEVICE_GATE",
    "GATE_REASON_LOW_CONFIDENCE",
    "GATE_REASON_QUIET_HOURS",
    "GATE_REASON_WAKE_COOLDOWN",
    "GATE_STATUS_BLOCKED",
    "GATE_STATUS_NOT_REQUESTED",
    "GATE_STATUS_PASSED",
    "LAYER2_HANDOFF_ALLOWED_FIELDS",
    "LAYER2_HANDOFF_SCHEMA_VERSION",
    "LAYER2_HANDOFF_SOURCE_FIELDS",
    "LEGACY_CORE_WAKE_PACKAGE_SCHEMA_VERSION",
    "LEGACY_SENTINEL_RUNTIME_CONTEXT_SCHEMA_VERSION",
    "REQUIRED_SENTINEL_JUDGMENT_FIELDS",
    "ReplayEvidenceBundle",
    "PLANNED_CORE_WAKE_PRODUCTION_EFFECTS",
    "SENTINEL_CHAIN_DRY_RUN_SCHEMA_VERSION",
    "SENTINEL_JUDGMENT_EVAL_SCHEMA_VERSION",
    "SENTINEL_JUDGMENT_PROMPT_VERSION",
    "SENTINEL_JUDGMENT_RUN_SCHEMA_VERSION",
    "SENTINEL_JUDGMENT_SCHEMA_VERSION",
    "SENTINEL_GATE_RESULT_SCHEMA_VERSION",
    "WAKE_BOUNDARY_RESULT_SCHEMA_VERSION",
    "SENTINEL_REPLAY_EVAL_SCHEMA_VERSION",
    "SENTINEL_RUNTIME_CONTEXT_SCHEMA_VERSION",
    "SUPPORTED_CORE_WAKE_PACKAGE_SCHEMA_VERSIONS",
    "SUPPORTED_SENTINEL_RUNTIME_CONTEXT_SCHEMA_VERSIONS",
    "SentinelEvidenceService",
    "SentinelEvidenceView",
    "SentinelJudgmentProvider",
    "CoreWakePorts",
    "actual_judgment_payload",
    "adapt_replay_input",
    "attention_snapshot_builder",
    "build_attention_snapshot",
    "build_attention_snapshot_from_case",
    "build_core_wake_preflight",
    "build_core_wake_package",
    "build_layer2_handoff",
    "build_sentinel_runtime_context",
    "build_sentinel_judgment_messages",
    "evaluate_case",
    "evaluate_cases",
    "evaluate_judgment_case",
    "evaluate_judgment_cases",
    "evaluate_judgment_expectations",
    "evaluate_sentinel_gate",
    "evaluate_wake_boundaries",
    "judgment_to_monitor_log_fields",
    "normalize_sentinel_judgment",
    "parse_sentinel_judgment",
    "resolve_attention_config",
    "run_core_wake_orchestrator_dry_run",
    "run_core_wake_orchestrator_full_execute",
    "run_core_wake_orchestrator_test_execute",
    "run_sentinel_chain_dry_run",
    "run_sentinel_judgment_dry_run",
    "sentinel_evidence_service",
    "stored_message_to_dict",
    "validate_core_wake_ports",
    "validate_sentinel_runtime_context",
]
